### ISSUE TITLE
Update for React Router 3

### ISSUE THREAD

**Issue by steida** [taion/react-router-scroll#28]
How can I help? I need it because I need https://github.com/jmurzy/react-router-native asap. Since Este is universal dev stack, I can not go with two different React Routers.

**Comment by taion** [comment]
Huh? Does react-router-native depend on React Router v3?

**Comment by steida** [comment]
Exactly. And it's great design decision. Finally we have the same routing and universal (native) routing.

**Comment by taion** [comment]
I want to resolve https://github.com/taion/scroll-behavior/pull/86 and the corresponding PR here first. It's not really worth it to try to support both, so I want to cut a history v2 compatible release with the scroll container support (after I finish setting up the API in both places).

**Comment by aaronjensen** [comment]
@taion now that those are resolved can an alpha release be cut for testing w/ react-router 3 alpha?

**Comment by steida** [comment]
@taion Please, can you release alpha for react-router 3?

**Comment by taion** [comment]
Hit me up on Twitter DM or Reactiflux.

**Comment by taion** [comment]
Okay, so the problem is, until https://github.com/mjackson/history/pull/316 is pulled into a history v3 release, scroll management will be almost entirely non-functional with hash histories. It's not impossible to work around this in scroll-behavior (essentially just always ignore key), but it will be nasty, and I don't really want to do that... so I'm not really comfortable doing that right now.

Also, given React Router v4 being on the horizon, I'm not entirely sure I want to upgrade to React Router v3 at all, since it looks there won't be the opportunity to meaningfully fix any of the use cases I currently have trouble with.

I'd be happy to accept a PR to scroll-behavior that adds history v3 support, and to cut a prerelease from there on both repos, but it's going to be suboptimal.

**Comment by steida** [comment]
Ok, let's wait for React Router 4.

**Comment by taion** [comment]
FWIW, React Router v4 is almost entirely different, so I'm not sure there can or will be an update of this library for React Router v4.

**Comment by aaronjensen** [comment]
React Router v3 fixes some issues with redux and withRouter so it'd be nice to have that. Who knows how long react router v4 will take: https://github.com/reactjs/react-router/pull/3443

**Comment by rogchap** [comment]
Worth updating the install steps in the docs as `history` is at v3. 
When doing an npm install you get this warning:
```bash
npm WARN scroll-behavior@0.8.1 requires a peer of history@^1.12.1 || ^2.0.0 but none was installed.
```

Which is totally fine, but most people (which is what I did) will just do an `npm install history`. This will install history v3, which seems to break this component.

What you really want is `history@2.1.2`

**Comment by taion** [comment]
The install steps here do not include `npm i history`. None of the packages involved here have history as a peer dependency.

**Comment by rogchap** [comment]
Hmmm... I wonder where I'm getting this warning from..

**Comment by taion** [comment]
Well, if you install history yourself, you're going to get v3, which you don't want. Worth adding a note about this to the README.

**Comment by donaldpipowitch** [comment]
Can someone please explain me which react-router version, which history version and which  history implementation (browser history vs. hash history) will be supported in the future? I'm a little bit confused about the current strategy. Sorry.

**Comment by taion** [comment]
With this library, use RR v2.x with history v2.x. I can't comment on future support. I don't plan on further updating this library at the moment.

**Comment by SimenB** [comment]
Could a note be added to the top of the readme about this? Just spent half an hour (not a lot sure, but completely unnecessary) on this before finding this issue. The fact it doesn't work for `react-router@latest` when a lot of google results points to this lib, is kinda sad.

It's fine it doesn't work, I'd just like to be told so early. From what I can tell the reason it doesn't work is because I'm using hash history

**Comment by taion** [comment]
This is a bug in history. You can follow up on https://github.com/mjackson/history/pull/316 if you want. It's not my problem here.

**Comment by SimenB** [comment]
Sure, I understand that that, but a note at the top of the readme would still be nice :smile: I can provide a pr for it if you're interested?

**Comment by taion** [comment]
I don't think it makes sense to add a note here regarding what's clearly a bug in another library.
